name: NASA project CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use NodeJS version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install --prefix server
      - run: npm install --prefix client
      - run: npm run build --prefix client
